version: '3.8'

services:
  postgres-scores:
    image: postgres:15-alpine
    container_name: hackathon-scores-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scores_password
      POSTGRES_DB: hackathon_scores
    ports:
      - "5437:5432" # Використовуємо порт 5437, щоб не конфліктувати з тим, що у тебе вже запущено на 5436
    volumes:
      - postgres_scores_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_scores_data:
